version: '3'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ./es_data_volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      interval: 10s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'


  web:
    build: .
    container_name: web
    links:
      - "es:elasticsearch"
    volumes:
      - ./:/code
    ports:
      - 8001:8001
    depends_on:
      es:
        condition: service_healthy
    restart: on-failure
